### ISSUE TITLE
Dashboard - Doc name with no capitalization & plurals

### ISSUE THREAD

**Issue by fxbenard** [devinsays/documentation-post-type#3]
Improvement : in the "d'un coup d'oeil" area, as it is for posts and pages ;)

**Comment by devinsays** [comment]
Sorry, this is still a little unclear to me. Can you post a screenshot or link to the spot in the code that needs to be updated?

**Comment by fxbenard** [comment]
Sorry, it should help
![doc-improvement](https://cloud.githubusercontent.com/assets/802114/6056322/58e5b550-ad0f-11e4-9d07-4dc8a2aa4d54.jpg)

**Comment by devinsays** [comment]
The best way to change that is to update the "name" of the label. See: 36f5375f1cde40a8a87b358d56d46578b763bc27

We actually don't have a plural label called "Docs", the "name" label is generally used as the plural. However, when we update this all instances of "Documentation" are changes to "Docs".

Let me know if you want to re-open and revisit.

**Comment by fxbenard** [comment]
Ok, no we can't update the name cause if so, the dasboard menu will be wrong. Leave it like that

**Comment by devinsays** [comment]
Okay, reverted.
